language: generic
sudo: required
dist: trusty

os: 
- osx
- linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-4.2
    
matrix:
  include:
    - os: linux
      compiler: gcc-5
      env: COMPILER="g++-5"
    - os: osx
      compiler: clang-4.2
      env: COMPILER="clang++-4.2"
        
script:
- cmake -H. -B_builds
- cmake --build _builds/
- cmake --build _builds/ --target test
