language: generic
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    packages:
    - clang-4.2.1
    
matrix:
  include:
    - os: linux
      compiler: clang-3.6
      env: COMPILER="clang++-3.6"
    - os: osx
      compiler: clang-3.6
      env: COMPILER="clang++-3.6"
        
script:
- cmake -H. -B_builds
- cmake --build _builds/
- cmake --build _builds/ --target test
