language: generic
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - ccache
      - clang-3.6
      - gcc-5
    sources:
      - llvm-toolchain-trusty-3.6
      - ubuntu-toolchain-r-test
    
matrix:
  include:
    - os: linux
      compiler: clang-3.6
      env: COMPILER="clang++-3.6"
    - os: osx
      compiler: clang-3.6
      env: COMPILER="clang++-3.6"
        
script:
- cmake -H. -B_builds
- cmake --build _builds/
- cmake --build _builds/ --target test
