language: cpp

os: 
 - linux
 - osx
 
before_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update -qq;
    sudo apt-get install libboost-dev;
  fi;
          
script:
- mkdir build && cd build
- cmake ..
- make
- ctest
